GET http://localhost:3001/api/attivita HTTP/1.1
GET http://localhost:3001/api/attivita/classe/gestione_tempo HTTP/1.1



POST http://localhost:3001/api/attivita HTTP/1.1
Content-Type: application/json


{
  "date":"febbraio",
  "classe": "-class",
  "id_user":2,
  "tipo":"bro",
  "valore":"val"

}


POST http://localhost:3001/api/registrazione HTTP/1.1
Content-Type: application/json


{
"email":"ttt@gmail.com",
"password":"Helloword123!",
"course":"judo"

}



DELETE http://localhost:3001/api/train/0 HTTP/1.1